version: '3.8'

services:
  app:
    container_name: stas_zaverecny_app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app
    ports:
      - "12121:3000"
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:17
    networks:
      - app
    container_name: stas_zaverecny_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - /home/stasik/volumes/zaverecny/pg:/var/lib/postgresql/data

networks:
  app:
    driver: bridge
